//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Couchcoding.Logbert.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Couchcoding.Logbert.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap action_add_16xMD {
            get {
                object obj = ResourceManager.GetObject("action_add_16xMD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_Down_16xLG {
            get {
                object obj = ResourceManager.GetObject("arrow_Down_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_Up_16xLG {
            get {
                object obj = ResourceManager.GetObject("arrow_Up_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Debug_Light {
            get {
                object obj = ResourceManager.GetObject("Debug_Light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Error_Light {
            get {
                object obj = ResourceManager.GetObject("Error_Light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eyedropper_16xLG {
            get {
                object obj = ResourceManager.GetObject("eyedropper_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fatal_Light {
            get {
                object obj = ResourceManager.GetObject("Fatal_Light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindSymbol_6263 {
            get {
                object obj = ResourceManager.GetObject("FindSymbol_6263", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font_color {
            get {
                object obj = ResourceManager.GetObject("font_color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Info_Light {
            get {
                object obj = ResourceManager.GetObject("Info_Light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap log_error {
            get {
                object obj = ResourceManager.GetObject("log_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logbert_about {
            get {
                object obj = ResourceManager.GetObject("logbert_about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logbert_Logo_Background {
            get {
                object obj = ResourceManager.GetObject("Logbert_Logo_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logbert_Start_Screen {
            get {
                object obj = ResourceManager.GetObject("Logbert_Start_Screen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogLevel_16x {
            get {
                object obj = ResourceManager.GetObject("LogLevel_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NoBookmark {
            get {
                object obj = ResourceManager.GetObject("NoBookmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PencilAngled_16xMD_color {
            get {
                object obj = ResourceManager.GetObject("PencilAngled_16xMD_color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap properties_16xLG {
            get {
                object obj = ResourceManager.GetObject("properties_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Remove_16xMD {
            get {
                object obj = ResourceManager.GetObject("Remove_16xMD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RunTests_8790 {
            get {
                object obj = ResourceManager.GetObject("RunTests_8790", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Script_16x {
            get {
                object obj = ResourceManager.GetObject("Script_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusAnnotations_Information_16xLG {
            get {
                object obj = ResourceManager.GetObject("StatusAnnotations_Information_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2022 Couchcoding. All Right Reserved..
        /// </summary>
        internal static string strAboutDlgCopyright {
            get {
                return ResourceManager.GetString("strAboutDlgCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string strAboutDlgVersion {
            get {
                return ResourceManager.GetString("strAboutDlgVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*.
        /// </summary>
        internal static string strAllFilesPattern {
            get {
                return ResourceManager.GetString("strAllFilesPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear Items.
        /// </summary>
        internal static string strClearMruList {
            get {
                return ResourceManager.GetString("strClearMruList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.*).
        /// </summary>
        internal static string strColumnizerColumnDefaultExpresssion {
            get {
                return ResourceManager.GetString("strColumnizerColumnDefaultExpresssion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Column.
        /// </summary>
        internal static string strColumnizerColumnDefaultName {
            get {
                return ResourceManager.GetString("strColumnizerColumnDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least one columnizer with a name and an expression..
        /// </summary>
        internal static string strColumnizerConfigurationAddAtLeastOneRow {
            get {
                return ResourceManager.GetString("strColumnizerConfigurationAddAtLeastOneRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name and an expression for each configure column..
        /// </summary>
        internal static string strColumnizerConfigurationEnterColumnNameAndExpression {
            get {
                return ResourceManager.GetString("strColumnizerConfigurationEnterColumnNameAndExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the columnizer..
        /// </summary>
        internal static string strColumnizerConfigurationPleaseEnterName {
            get {
                return ResourceManager.GetString("strColumnizerConfigurationPleaseEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Columnizer.
        /// </summary>
        internal static string strColumnizerDefaultName {
            get {
                return ResourceManager.GetString("strColumnizerDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory does not exists. Please select an existing one..
        /// </summary>
        internal static string strCustomDirectodyReceiverDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("strCustomDirectodyReceiverDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file pattern specified. Please enter a valie one like &apos;.*\.log[\.]?[\d]?&apos;..
        /// </summary>
        internal static string strCustomDirectodyReceiverInvalidFilePattern {
            get {
                return ResourceManager.GetString("strCustomDirectodyReceiverInvalidFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the log directory to observe..
        /// </summary>
        internal static string strCustomDirectoryReceiverSelectDirectoryToObserve {
            get {
                return ResourceManager.GetString("strCustomDirectoryReceiverSelectDirectoryToObserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No columnizer is selected. Please choose an existing, or create a new one..
        /// </summary>
        internal static string strCustomDirReceiverNoColumnizerSelected {
            get {
                return ResourceManager.GetString("strCustomDirReceiverNoColumnizerSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given log file does not exist. Please select an existing one..
        /// </summary>
        internal static string strCustomFileReceiverFileDoesNotExist {
            get {
                return ResourceManager.GetString("strCustomFileReceiverFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No columnizer is selected. Please choose an existing, or create a new one..
        /// </summary>
        internal static string strCustomFileReceiverNoColumnizerSelected {
            get {
                return ResourceManager.GetString("strCustomFileReceiverNoColumnizerSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:{0}{1}{2}.
        /// </summary>
        internal static string strCustomTcpReceiverNetworkDescription {
            get {
                return ResourceManager.GetString("strCustomTcpReceiverNetworkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address:{0}{1}{2}.
        /// </summary>
        internal static string strCustomTcpReceiverNetworkIPAddress {
            get {
                return ResourceManager.GetString("strCustomTcpReceiverNetworkIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:{0}{0}{1} MBit/s{2}.
        /// </summary>
        internal static string strCustomTcpReceiverNetworkSpeed {
            get {
                return ResourceManager.GetString("strCustomTcpReceiverNetworkSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No columnizer is selected. Please choose an existing, or create a new one..
        /// </summary>
        internal static string strCustomTcpReceiverNoColumnizerSelected {
            get {
                return ResourceManager.GetString("strCustomTcpReceiverNoColumnizerSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network interface available to listen on..
        /// </summary>
        internal static string strCustomTcpReceiverNoNetworkInterfaceAvailable {
            get {
                return ResourceManager.GetString("strCustomTcpReceiverNoNetworkInterfaceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given IP address is invalid..
        /// </summary>
        internal static string strCustomUdpReceiverInvalidIpAddress {
            get {
                return ResourceManager.GetString("strCustomUdpReceiverInvalidIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:{0}{1}{2}.
        /// </summary>
        internal static string strCustomUdpReceiverNetworkDescription {
            get {
                return ResourceManager.GetString("strCustomUdpReceiverNetworkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address:{0}{1}{2}.
        /// </summary>
        internal static string strCustomUdpReceiverNetworkIPAddress {
            get {
                return ResourceManager.GetString("strCustomUdpReceiverNetworkIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:{0}{0}{1} MBit/s{2}.
        /// </summary>
        internal static string strCustomUdpReceiverNetworkSpeed {
            get {
                return ResourceManager.GetString("strCustomUdpReceiverNetworkSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No columnizer is selected. Please choose an existing, or create a new one..
        /// </summary>
        internal static string strCustomUdpReceiverNoColumnizerSelected {
            get {
                return ResourceManager.GetString("strCustomUdpReceiverNoColumnizerSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network interface available to listen on..
        /// </summary>
        internal static string strCustomUdpReceiverNoNetworkInterfaceAvailable {
            get {
                return ResourceManager.GetString("strCustomUdpReceiverNoNetworkInterfaceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logbert Script.lua.
        /// </summary>
        internal static string strDefaultLuaFilename {
            get {
                return ResourceManager.GetString("strDefaultLuaFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string strDocumentErrorTitle {
            get {
                return ResourceManager.GetString("strDocumentErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information:.
        /// </summary>
        internal static string strDocumentInfoTitle {
            get {
                return ResourceManager.GetString("strDocumentInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        internal static string strDocumentMessageAllDisplayed {
            get {
                return ResourceManager.GetString("strDocumentMessageAllDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Messages ({1} displayed).
        /// </summary>
        internal static string strDocumentMessageCount {
            get {
                return ResourceManager.GetString("strDocumentMessageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Running.
        /// </summary>
        internal static string strDocumentStatusRunning {
            get {
                return ResourceManager.GetString("strDocumentStatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Stopped.
        /// </summary>
        internal static string strDocumentStatusStopped {
            get {
                return ResourceManager.GetString("strDocumentStatusStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning:.
        /// </summary>
        internal static string strDocumentWarnTitle {
            get {
                return ResourceManager.GetString("strDocumentWarnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading script: {0}.
        /// </summary>
        internal static string strErrorLoadingScript {
            get {
                return ResourceManager.GetString("strErrorLoadingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to open your webbrowser ({0})..
        /// </summary>
        internal static string strErrorOpeningSystemBrowser {
            get {
                return ResourceManager.GetString("strErrorOpeningSystemBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving script: {0}.
        /// </summary>
        internal static string strErrorSavingScript {
            get {
                return ResourceManager.GetString("strErrorSavingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string strEventLogReceiverNoCategory {
            get {
                return ResourceManager.GetString("strEventLogReceiverNoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No event log name available to listen for..
        /// </summary>
        internal static string strEventLogReceiverNoLogNameAvailable {
            get {
                return ResourceManager.GetString("strEventLogReceiverNoLogNameAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No machine name to listen on is set..
        /// </summary>
        internal static string strEventLogReceiverNoMachineName {
            get {
                return ResourceManager.GetString("strEventLogReceiverNoMachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string strEventLogReceiverNoUsername {
            get {
                return ResourceManager.GetString("strEventLogReceiverNoUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*|General Log Files (*.log)|*.log.
        /// </summary>
        internal static string strFileLoadPattern {
            get {
                return ResourceManager.GetString("strFileLoadPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Filter.
        /// </summary>
        internal static string strFilterDlgEditFilter {
            get {
                return ResourceManager.GetString("strFilterDlgEditFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string strFilterNotMatchEndTag {
            get {
                return ResourceManager.GetString("strFilterNotMatchEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT (.
        /// </summary>
        internal static string strFilterNotMatchStartTag {
            get {
                return ResourceManager.GetString("strFilterNotMatchStartTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory does not exists. Please select an existing one..
        /// </summary>
        internal static string strLog4NetDirectodyReceiverDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("strLog4NetDirectodyReceiverDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file pattern specified. Please enter a valie one like &apos;.*\.log[\.]?[\d]?&apos;..
        /// </summary>
        internal static string strLog4NetDirectodyReceiverInvalidFilePattern {
            get {
                return ResourceManager.GetString("strLog4NetDirectodyReceiverInvalidFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the log directory to observe..
        /// </summary>
        internal static string strLog4NetDirectoryReceiverSelectDirectoryToObserve {
            get {
                return ResourceManager.GetString("strLog4NetDirectoryReceiverSelectDirectoryToObserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given log file does not exist. Please select an existing one..
        /// </summary>
        internal static string strLog4NetFileReceiverFileDoesNotExist {
            get {
                return ResourceManager.GetString("strLog4NetFileReceiverFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*|Log4Net Files (*.log)|*.log.
        /// </summary>
        internal static string strLog4NetFileReceiverFilePattern {
            get {
                return ResourceManager.GetString("strLog4NetFileReceiverFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given IP address is invalid..
        /// </summary>
        internal static string strLog4NetUdpReceiverInvalidIpAddress {
            get {
                return ResourceManager.GetString("strLog4NetUdpReceiverInvalidIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:{0}{1}{2}.
        /// </summary>
        internal static string strLog4NetUdpReceiverNetworkDescription {
            get {
                return ResourceManager.GetString("strLog4NetUdpReceiverNetworkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address:{0}{1}{2}.
        /// </summary>
        internal static string strLog4NetUdpReceiverNetworkIPAddress {
            get {
                return ResourceManager.GetString("strLog4NetUdpReceiverNetworkIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:{0}{0}{1} MBit/s{2}.
        /// </summary>
        internal static string strLog4NetUdpReceiverNetworkSpeed {
            get {
                return ResourceManager.GetString("strLog4NetUdpReceiverNetworkSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network interface available to listen on..
        /// </summary>
        internal static string strLog4NetUdpReceiverNoNetworkInterfaceAvailable {
            get {
                return ResourceManager.GetString("strLog4NetUdpReceiverNoNetworkInterfaceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Offset: {0} Milliseconds).
        /// </summary>
        internal static string strLoggerDetailsCtrlOffset {
            get {
                return ResourceManager.GetString("strLoggerDetailsCtrlOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger Root.
        /// </summary>
        internal static string strLoggerRoot {
            get {
                return ResourceManager.GetString("strLoggerRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --[[
        ///
        ///Logbert Lua script interface
        ///
        ///There are some callback and calling functions you may use in this scripting window.
        ///All provided Lua methods are available. So be careful what you are doing!
        ///
        ///Callback Functions:
        ///
        ///  - OnMessagesReceived
        ///    This function is called if at least one message is received and displayed in the log window.
        ///    It provides all new received log messages as a Lua table as parameter.
        ///
        ///    OnMessagesReceived = function (msgs)
        ///      for k, v in pairs(msgs) do
        ///        ... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string strLuaEditorDefaultContent {
            get {
                return ResourceManager.GetString("strLuaEditorDefaultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing script: {0}{1}.
        /// </summary>
        internal static string strLuaEditorErrorExecutingScript {
            get {
                return ResourceManager.GetString("strLuaEditorErrorExecutingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Logbert Homepage could not be opened. Please open your browser and navigate to &quot;{0}&quot;..
        /// </summary>
        internal static string strMainUnableToOpenUri {
            get {
                return ResourceManager.GetString("strMainUnableToOpenUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string strMainUpdateAvailable {
            get {
                return ResourceManager.GetString("strMainUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0} Details to the Clipboard.
        /// </summary>
        internal static string strMessageDetailsCopyButtonTooltip {
            get {
                return ResourceManager.GetString("strMessageDetailsCopyButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} could not be found anymore. Do you want to remove it from the recently used file list?.
        /// </summary>
        internal static string strMruFileCouldNotBeFound {
            get {
                return ResourceManager.GetString("strMruFileCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Settings.
        /// </summary>
        internal static string strNewLoggerPanelText {
            get {
                return ResourceManager.GetString("strNewLoggerPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory does not exists. Please select an existing one..
        /// </summary>
        internal static string strNLogDirectodyReceiverDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("strNLogDirectodyReceiverDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file pattern specified. Please enter a valie one like &apos;.*\.log[\.]?[\d]?&apos;..
        /// </summary>
        internal static string strNLogDirectodyReceiverInvalidFilePattern {
            get {
                return ResourceManager.GetString("strNLogDirectodyReceiverInvalidFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the log directory to observe..
        /// </summary>
        internal static string strNLogDirectoryReceiverSelectDirectoryToObserve {
            get {
                return ResourceManager.GetString("strNLogDirectoryReceiverSelectDirectoryToObserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given log file does not exist. Please select an existing one..
        /// </summary>
        internal static string strNLogFileReceiverFileDoesNotExist {
            get {
                return ResourceManager.GetString("strNLogFileReceiverFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*|NLog Files (*.log)|*.log.
        /// </summary>
        internal static string strNLogFileReceiverFilePattern {
            get {
                return ResourceManager.GetString("strNLogFileReceiverFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:{0}{1}{2}.
        /// </summary>
        internal static string strNlogTcpReceiverNetworkDescription {
            get {
                return ResourceManager.GetString("strNlogTcpReceiverNetworkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address:{0}{1}{2}.
        /// </summary>
        internal static string strNlogTcpReceiverNetworkIPAddress {
            get {
                return ResourceManager.GetString("strNlogTcpReceiverNetworkIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:{0}{0}{1} MBit/s{2}.
        /// </summary>
        internal static string strNlogTcpReceiverNetworkSpeed {
            get {
                return ResourceManager.GetString("strNlogTcpReceiverNetworkSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network interface available to listen on..
        /// </summary>
        internal static string strNlogTcpReceiverNoNetworkInterfaceAvailable {
            get {
                return ResourceManager.GetString("strNlogTcpReceiverNoNetworkInterfaceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given IP address is invalid..
        /// </summary>
        internal static string strNLogUdpReceiverInvalidIpAddress {
            get {
                return ResourceManager.GetString("strNLogUdpReceiverInvalidIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:{0}{1}{2}.
        /// </summary>
        internal static string strNLogUdpReceiverNetworkDescription {
            get {
                return ResourceManager.GetString("strNLogUdpReceiverNetworkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address:{0}{1}{2}.
        /// </summary>
        internal static string strNLogUdpReceiverNetworkIPAddress {
            get {
                return ResourceManager.GetString("strNLogUdpReceiverNetworkIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:{0}{0}{1} MBit/s{2}.
        /// </summary>
        internal static string strNLogUdpReceiverNetworkSpeed {
            get {
                return ResourceManager.GetString("strNLogUdpReceiverNetworkSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network interface available to listen on..
        /// </summary>
        internal static string strNLogUdpReceiverNoNetworkInterfaceAvailable {
            get {
                return ResourceManager.GetString("strNLogUdpReceiverNoNetworkInterfaceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; could not be open as a log file. 
        ///Maybe the data the file contains is not yet supported by Logbert..
        /// </summary>
        internal static string strOpenLogFileError {
            get {
                return ResourceManager.GetString("strOpenLogFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*|Lua scripts (*.lua)|*.lua.
        /// </summary>
        internal static string strOpenLuaFilter {
            get {
                return ResourceManager.GetString("strOpenLuaFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to adjust the level back- and foreground colors to match the new selected application theme &quot;{0}&quot;?.
        /// </summary>
        internal static string strOptionPanelFontColorApplyColorScheme {
            get {
                return ResourceManager.GetString("strOptionPanelFontColorApplyColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string strOptionPanelFontColorCustomColor {
            get {
                return ResourceManager.GetString("strOptionPanelFontColorCustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font and Color.
        /// </summary>
        internal static string strOptionPanelFontColorName {
            get {
                return ResourceManager.GetString("strOptionPanelFontColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string strOptionPanelGeneral {
            get {
                return ResourceManager.GetString("strOptionPanelGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string strOptionPanelPleaseWait {
            get {
                return ResourceManager.GetString("strOptionPanelPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Editor.
        /// </summary>
        internal static string strOptionPanelScriptEditor {
            get {
                return ResourceManager.GetString("strOptionPanelScriptEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.txt.
        /// </summary>
        internal static string strSaveLogDefaultName {
            get {
                return ResourceManager.GetString("strSaveLogDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while writing the logged messages to the file: {0}.
        /// </summary>
        internal static string strSaveLogErrorOccured {
            get {
                return ResourceManager.GetString("strSaveLogErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*|General CSV Files (*.csv)|*.csv.
        /// </summary>
        internal static string strSaveLogToCSVFilePattern {
            get {
                return ResourceManager.GetString("strSaveLogToCSVFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*|General Text Files (*.txt)|*.txt.
        /// </summary>
        internal static string strSaveLogToTextFilePattern {
            get {
                return ResourceManager.GetString("strSaveLogToTextFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*|Lua scripts (*.lua)|*.lua.
        /// </summary>
        internal static string strSaveLuaFilter {
            get {
                return ResourceManager.GetString("strSaveLuaFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given log file does not exist. Please select an existing one..
        /// </summary>
        internal static string strSyslogFileReceiverFileDoesNotExist {
            get {
                return ResourceManager.GetString("strSyslogFileReceiverFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*|Syslog Files (*.log)|*.log.
        /// </summary>
        internal static string strSyslogFileReceiverFilePattern {
            get {
                return ResourceManager.GetString("strSyslogFileReceiverFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid timestamp format, or select a predefined one..
        /// </summary>
        internal static string strSyslogFileReceiverTimestampNotSpecified {
            get {
                return ResourceManager.GetString("strSyslogFileReceiverTimestampNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} timestamp formats defined. (Click &apos;...&apos; to edit).
        /// </summary>
        internal static string strSyslogReceiverCountOfTimestampsDefined {
            get {
                return ResourceManager.GetString("strSyslogReceiverCountOfTimestampsDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given IP address is invalid..
        /// </summary>
        internal static string strSyslogReceiverInvalidIpAddress {
            get {
                return ResourceManager.GetString("strSyslogReceiverInvalidIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network interface available to listen on..
        /// </summary>
        internal static string strSyslogReceiverNoNetworkInterfaceAvailable {
            get {
                return ResourceManager.GetString("strSyslogReceiverNoNetworkInterfaceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid timestamp format, or select a predefined one..
        /// </summary>
        internal static string strSyslogUdpReceiverTimestampNotSpecified {
            get {
                return ResourceManager.GetString("strSyslogUdpReceiverTimestampNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkown Error.
        /// </summary>
        internal static string strValidationResultUnkownError {
            get {
                return ResourceManager.GetString("strValidationResultUnkownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trace_Light {
            get {
                object obj = ResourceManager.GetObject("Trace_Light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VSO_Time_16x {
            get {
                object obj = ResourceManager.GetObject("VSO_Time_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Warn_Light {
            get {
                object obj = ResourceManager.GetObject("Warn_Light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
