//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Couchcoding.Logbert.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color BackgroundColorTrace {
            get {
                return ((global::System.Drawing.Color)(this["BackgroundColorTrace"]));
            }
            set {
                this["BackgroundColorTrace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color BackgroundColorDebug {
            get {
                return ((global::System.Drawing.Color)(this["BackgroundColorDebug"]));
            }
            set {
                this["BackgroundColorDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue")]
        public global::System.Drawing.Color BackgroundColorInfo {
            get {
                return ((global::System.Drawing.Color)(this["BackgroundColorInfo"]));
            }
            set {
                this["BackgroundColorInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color BackgroundColorWarning {
            get {
                return ((global::System.Drawing.Color)(this["BackgroundColorWarning"]));
            }
            set {
                this["BackgroundColorWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightCoral")]
        public global::System.Drawing.Color BackgroundColorError {
            get {
                return ((global::System.Drawing.Color)(this["BackgroundColorError"]));
            }
            set {
                this["BackgroundColorError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color BackgroundColorFatal {
            get {
                return ((global::System.Drawing.Color)(this["BackgroundColorFatal"]));
            }
            set {
                this["BackgroundColorFatal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForegroundColorTrace {
            get {
                return ((global::System.Drawing.Color)(this["ForegroundColorTrace"]));
            }
            set {
                this["ForegroundColorTrace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForegroundColorDebug {
            get {
                return ((global::System.Drawing.Color)(this["ForegroundColorDebug"]));
            }
            set {
                this["ForegroundColorDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForegroundColorInfo {
            get {
                return ((global::System.Drawing.Color)(this["ForegroundColorInfo"]));
            }
            set {
                this["ForegroundColorInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForegroundColorWarning {
            get {
                return ((global::System.Drawing.Color)(this["ForegroundColorWarning"]));
            }
            set {
                this["ForegroundColorWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForegroundColorError {
            get {
                return ((global::System.Drawing.Color)(this["ForegroundColorError"]));
            }
            set {
                this["ForegroundColorError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForegroundColorFatal {
            get {
                return ((global::System.Drawing.Color)(this["ForegroundColorFatal"]));
            }
            set {
                this["ForegroundColorFatal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HH:mm:ss.fff")]
        public string TimestampFormat {
            get {
                return ((string)(this["TimestampFormat"]));
            }
            set {
                this["TimestampFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int UiRefreshIntervalMs {
            get {
                return ((int)(this["UiRefreshIntervalMs"]));
            }
            set {
                this["UiRefreshIntervalMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif")]
        public string LogMessagesFontName {
            get {
                return ((string)(this["LogMessagesFontName"]));
            }
            set {
                this["LogMessagesFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public float LogMessagesFontSize {
            get {
                return ((float)(this["LogMessagesFontSize"]));
            }
            set {
                this["LogMessagesFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection FrmFindSearchValue {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FrmFindSearchValue"]));
            }
            set {
                this["FrmFindSearchValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrmFindSearchMatchCase {
            get {
                return ((bool)(this["FrmFindSearchMatchCase"]));
            }
            set {
                this["FrmFindSearchMatchCase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrmFindSearchMatchWholeWord {
            get {
                return ((bool)(this["FrmFindSearchMatchWholeWord"]));
            }
            set {
                this["FrmFindSearchMatchWholeWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrmFindSearchUseRegex {
            get {
                return ((bool)(this["FrmFindSearchUseRegex"]));
            }
            set {
                this["FrmFindSearchUseRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrmFindSearchUseWildcard {
            get {
                return ((bool)(this["FrmFindSearchUseWildcard"]));
            }
            set {
                this["FrmFindSearchUseWildcard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size FrmMainFormSize {
            get {
                return ((global::System.Drawing.Size)(this["FrmMainFormSize"]));
            }
            set {
                this["FrmMainFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState FrmMainFormState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["FrmMainFormState"]));
            }
            set {
                this["FrmMainFormState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FrmMainFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["FrmMainFormLocation"]));
            }
            set {
                this["FrmMainFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle FontStyleTrace {
            get {
                return ((global::System.Drawing.FontStyle)(this["FontStyleTrace"]));
            }
            set {
                this["FontStyleTrace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle FontStyleDebug {
            get {
                return ((global::System.Drawing.FontStyle)(this["FontStyleDebug"]));
            }
            set {
                this["FontStyleDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle FontStyleInfo {
            get {
                return ((global::System.Drawing.FontStyle)(this["FontStyleInfo"]));
            }
            set {
                this["FontStyleInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle FontStyleWarning {
            get {
                return ((global::System.Drawing.FontStyle)(this["FontStyleWarning"]));
            }
            set {
                this["FontStyleWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle FontStyleError {
            get {
                return ((global::System.Drawing.FontStyle)(this["FontStyleError"]));
            }
            set {
                this["FontStyleError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle FontStyleFatal {
            get {
                return ((global::System.Drawing.FontStyle)(this["FontStyleFatal"]));
            }
            set {
                this["FontStyleFatal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlSyslogSettingsInterface {
            get {
                return ((string)(this["PnlSyslogSettingsInterface"]));
            }
            set {
                this["PnlSyslogSettingsInterface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlSyslogSettingsMulticastAddress {
            get {
                return ((string)(this["PnlSyslogSettingsMulticastAddress"]));
            }
            set {
                this["PnlSyslogSettingsMulticastAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlLog4NetUdpSettingsInterface {
            get {
                return ((string)(this["PnlLog4NetUdpSettingsInterface"]));
            }
            set {
                this["PnlLog4NetUdpSettingsInterface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlLog4NetFileSettingsFile {
            get {
                return ((string)(this["PnlLog4NetFileSettingsFile"]));
            }
            set {
                this["PnlLog4NetFileSettingsFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7071")]
        public int PnlLog4NetUdpSettingsPort {
            get {
                return ((int)(this["PnlLog4NetUdpSettingsPort"]));
            }
            set {
                this["PnlLog4NetUdpSettingsPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PnlLog4NetFileSettingsStartFromBeginning {
            get {
                return ((bool)(this["PnlLog4NetFileSettingsStartFromBeginning"]));
            }
            set {
                this["PnlLog4NetFileSettingsStartFromBeginning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PnlSyslogSettingsJoinMulticast {
            get {
                return ((bool)(this["PnlSyslogSettingsJoinMulticast"]));
            }
            set {
                this["PnlSyslogSettingsJoinMulticast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("514")]
        public int PnlSyslogSettingsPort {
            get {
                return ((int)(this["PnlSyslogSettingsPort"]));
            }
            set {
                this["PnlSyslogSettingsPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlSyslogFileSettingsFile {
            get {
                return ((string)(this["PnlSyslogFileSettingsFile"]));
            }
            set {
                this["PnlSyslogFileSettingsFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PnlSyslogFileSettingsStartFromBeginning {
            get {
                return ((bool)(this["PnlSyslogFileSettingsStartFromBeginning"]));
            }
            set {
                this["PnlSyslogFileSettingsStartFromBeginning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogWndAutoScrollOnLastMessageSelect {
            get {
                return ((bool)(this["LogWndAutoScrollOnLastMessageSelect"]));
            }
            set {
                this["LogWndAutoScrollOnLastMessageSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MruManagerFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MruManagerFiles"]));
            }
            set {
                this["MruManagerFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FrmMainAllowOnlyOneInstance {
            get {
                return ((bool)(this["FrmMainAllowOnlyOneInstance"]));
            }
            set {
                this["FrmMainAllowOnlyOneInstance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlEventLogSettingsLogName {
            get {
                return ((string)(this["PnlEventLogSettingsLogName"]));
            }
            set {
                this["PnlEventLogSettingsLogName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".")]
        public string PnlEventLogSettingsMachineName {
            get {
                return ((string)(this["PnlEventLogSettingsMachineName"]));
            }
            set {
                this["PnlEventLogSettingsMachineName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlEventLogSettingsSourceName {
            get {
                return ((string)(this["PnlEventLogSettingsSourceName"]));
            }
            set {
                this["PnlEventLogSettingsSourceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif")]
        public string ScriptEditorFontName {
            get {
                return ((string)(this["ScriptEditorFontName"]));
            }
            set {
                this["ScriptEditorFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int ScriptEditorFontSize {
            get {
                return ((int)(this["ScriptEditorFontSize"]));
            }
            set {
                this["ScriptEditorFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ScriptEditorTabSize {
            get {
                return ((int)(this["ScriptEditorTabSize"]));
            }
            set {
                this["ScriptEditorTabSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScriptEditorUseSpacesForTabs {
            get {
                return ((bool)(this["ScriptEditorUseSpacesForTabs"]));
            }
            set {
                this["ScriptEditorUseSpacesForTabs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScriptEditorWordWrap {
            get {
                return ((bool)(this["ScriptEditorWordWrap"]));
            }
            set {
                this["ScriptEditorWordWrap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScriptEditorHighlightCurrentLine {
            get {
                return ((bool)(this["ScriptEditorHighlightCurrentLine"]));
            }
            set {
                this["ScriptEditorHighlightCurrentLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color CodeElement_DefaultText_ForegroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeElement_DefaultText_ForegroundColor"]));
            }
            set {
                this["CodeElement_DefaultText_ForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color CodeElement_DefaultText_BackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeElement_DefaultText_BackgroundColor"]));
            }
            set {
                this["CodeElement_DefaultText_BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle CodeElement_DefaultText_FontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["CodeElement_DefaultText_FontStyle"]));
            }
            set {
                this["CodeElement_DefaultText_FontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color CodeElement_Comment_ForegroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeElement_Comment_ForegroundColor"]));
            }
            set {
                this["CodeElement_Comment_ForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color CodeElement_Comment_BackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeElement_Comment_BackgroundColor"]));
            }
            set {
                this["CodeElement_Comment_BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle CodeElement_Comment_FontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["CodeElement_Comment_FontStyle"]));
            }
            set {
                this["CodeElement_Comment_FontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Olive")]
        public global::System.Drawing.Color CodeElement_Number_ForegroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeElement_Number_ForegroundColor"]));
            }
            set {
                this["CodeElement_Number_ForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color CodeElement_Number_BackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeElement_Number_BackgroundColor"]));
            }
            set {
                this["CodeElement_Number_BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle CodeElement_Number_FontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["CodeElement_Number_FontStyle"]));
            }
            set {
                this["CodeElement_Number_FontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color CodeElement_Keyword_ForegroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeElement_Keyword_ForegroundColor"]));
            }
            set {
                this["CodeElement_Keyword_ForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color CodeElement_Keyword_BackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeElement_Keyword_BackgroundColor"]));
            }
            set {
                this["CodeElement_Keyword_BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle CodeElement_Keyword_FontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["CodeElement_Keyword_FontStyle"]));
            }
            set {
                this["CodeElement_Keyword_FontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color CodeElement_LuaFunction_ForegroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeElement_LuaFunction_ForegroundColor"]));
            }
            set {
                this["CodeElement_LuaFunction_ForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color CodeElement_LuaFunction_BackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeElement_LuaFunction_BackgroundColor"]));
            }
            set {
                this["CodeElement_LuaFunction_BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle CodeElement_LuaFunction_FontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["CodeElement_LuaFunction_FontStyle"]));
            }
            set {
                this["CodeElement_LuaFunction_FontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teal")]
        public global::System.Drawing.Color CodeElement_LogbertFunction_ForegroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeElement_LogbertFunction_ForegroundColor"]));
            }
            set {
                this["CodeElement_LogbertFunction_ForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color CodeElement_LogbertFunction_BackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeElement_LogbertFunction_BackgroundColor"]));
            }
            set {
                this["CodeElement_LogbertFunction_BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle CodeElement_LogbertFunction_FontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["CodeElement_LogbertFunction_FontStyle"]));
            }
            set {
                this["CodeElement_LogbertFunction_FontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("163, 21, 21")]
        public global::System.Drawing.Color CodeElement_String_ForegroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeElement_String_ForegroundColor"]));
            }
            set {
                this["CodeElement_String_ForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color CodeElement_String_BackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeElement_String_BackgroundColor"]));
            }
            set {
                this["CodeElement_String_BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle CodeElement_String_FontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["CodeElement_String_FontStyle"]));
            }
            set {
                this["CodeElement_String_FontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Purple")]
        public global::System.Drawing.Color CodeElement_Operator_ForegroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeElement_Operator_ForegroundColor"]));
            }
            set {
                this["CodeElement_Operator_ForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color CodeElement_Operator_BackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeElement_Operator_BackgroundColor"]));
            }
            set {
                this["CodeElement_Operator_BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle CodeElement_Operator_FontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["CodeElement_Operator_FontStyle"]));
            }
            set {
                this["CodeElement_Operator_FontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BlueViolet")]
        public global::System.Drawing.Color CodeElement_Bracket_ForegroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeElement_Bracket_ForegroundColor"]));
            }
            set {
                this["CodeElement_Bracket_ForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color CodeElement_Bracket_BackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeElement_Bracket_BackgroundColor"]));
            }
            set {
                this["CodeElement_Bracket_BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle CodeElement_Bracket_FontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["CodeElement_Bracket_FontStyle"]));
            }
            set {
                this["CodeElement_Bracket_FontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlNLogTcpSettingsInterface {
            get {
                return ((string)(this["PnlNLogTcpSettingsInterface"]));
            }
            set {
                this["PnlNLogTcpSettingsInterface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7072")]
        public int PnlNLogTcpSettingsPort {
            get {
                return ((int)(this["PnlNLogTcpSettingsPort"]));
            }
            set {
                this["PnlNLogTcpSettingsPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlNLogUdpSettingsInterface {
            get {
                return ((string)(this["PnlNLogUdpSettingsInterface"]));
            }
            set {
                this["PnlNLogUdpSettingsInterface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7071")]
        public int PnlNLogUdpSettingsPort {
            get {
                return ((int)(this["PnlNLogUdpSettingsPort"]));
            }
            set {
                this["PnlNLogUdpSettingsPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlNLogFileSettingsFile {
            get {
                return ((string)(this["PnlNLogFileSettingsFile"]));
            }
            set {
                this["PnlNLogFileSettingsFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PnlNLogFileSettingsStartFromBeginning {
            get {
                return ((bool)(this["PnlNLogFileSettingsStartFromBeginning"]));
            }
            set {
                this["PnlNLogFileSettingsStartFromBeginning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlCustomFileSettingsFile {
            get {
                return ((string)(this["PnlCustomFileSettingsFile"]));
            }
            set {
                this["PnlCustomFileSettingsFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PnlCustomFileSettingsStartFromBeginning {
            get {
                return ((bool)(this["PnlCustomFileSettingsStartFromBeginning"]));
            }
            set {
                this["PnlCustomFileSettingsStartFromBeginning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlCustomFileSettingsColumnizer {
            get {
                return ((string)(this["PnlCustomFileSettingsColumnizer"]));
            }
            set {
                this["PnlCustomFileSettingsColumnizer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public int MaxLogMessages {
            get {
                return ((int)(this["MaxLogMessages"]));
            }
            set {
                this["MaxLogMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DockLayoutCustomReceiver {
            get {
                return ((string)(this["DockLayoutCustomReceiver"]));
            }
            set {
                this["DockLayoutCustomReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DockLayoutEventlogReceiver {
            get {
                return ((string)(this["DockLayoutEventlogReceiver"]));
            }
            set {
                this["DockLayoutEventlogReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DockLayoutLog4NetFileReceiver {
            get {
                return ((string)(this["DockLayoutLog4NetFileReceiver"]));
            }
            set {
                this["DockLayoutLog4NetFileReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DockLayoutLog4NetUdpReceiver {
            get {
                return ((string)(this["DockLayoutLog4NetUdpReceiver"]));
            }
            set {
                this["DockLayoutLog4NetUdpReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DockLayoutNLogFileReceiver {
            get {
                return ((string)(this["DockLayoutNLogFileReceiver"]));
            }
            set {
                this["DockLayoutNLogFileReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DockLayoutNLogTcpReceiver {
            get {
                return ((string)(this["DockLayoutNLogTcpReceiver"]));
            }
            set {
                this["DockLayoutNLogTcpReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DockLayoutNLogUdpReceiver {
            get {
                return ((string)(this["DockLayoutNLogUdpReceiver"]));
            }
            set {
                this["DockLayoutNLogUdpReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DockLayoutSyslogFileReceiver {
            get {
                return ((string)(this["DockLayoutSyslogFileReceiver"]));
            }
            set {
                this["DockLayoutSyslogFileReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DockLayoutSyslogUdpReceiver {
            get {
                return ((string)(this["DockLayoutSyslogUdpReceiver"]));
            }
            set {
                this["DockLayoutSyslogUdpReceiver"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("columnizer.xml")]
        public string ColumnizerRepository {
            get {
                return ((string)(this["ColumnizerRepository"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableColorMap {
            get {
                return ((bool)(this["EnableColorMap"]));
            }
            set {
                this["EnableColorMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48")]
        public int ColorMapAnnotation {
            get {
                return ((int)(this["ColorMapAnnotation"]));
            }
            set {
                this["ColorMapAnnotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FrmLogStatisticShowLegend {
            get {
                return ((bool)(this["FrmLogStatisticShowLegend"]));
            }
            set {
                this["FrmLogStatisticShowLegend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlLog4NetDirectorySettingsDirectory {
            get {
                return ((string)(this["PnlLog4NetDirectorySettingsDirectory"]));
            }
            set {
                this["PnlLog4NetDirectorySettingsDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".*\\.log[\\.]?[\\d]?")]
        public string PnlLog4NetDirectorySettingsPattern {
            get {
                return ((string)(this["PnlLog4NetDirectorySettingsPattern"]));
            }
            set {
                this["PnlLog4NetDirectorySettingsPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PnlLog4NetDirectorySettingsReadAllExisting {
            get {
                return ((bool)(this["PnlLog4NetDirectorySettingsReadAllExisting"]));
            }
            set {
                this["PnlLog4NetDirectorySettingsReadAllExisting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DockLayoutLog4NetDirReceiver {
            get {
                return ((string)(this["DockLayoutLog4NetDirReceiver"]));
            }
            set {
                this["DockLayoutLog4NetDirReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DockLayoutNLogDirReceiver {
            get {
                return ((string)(this["DockLayoutNLogDirReceiver"]));
            }
            set {
                this["DockLayoutNLogDirReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlNLogDirectorySettingsDirectory {
            get {
                return ((string)(this["PnlNLogDirectorySettingsDirectory"]));
            }
            set {
                this["PnlNLogDirectorySettingsDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".*\\.log[\\.]?[\\d]?")]
        public string PnlNLogDirectorySettingsPattern {
            get {
                return ((string)(this["PnlNLogDirectorySettingsPattern"]));
            }
            set {
                this["PnlNLogDirectorySettingsPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PnlNLogDirectorySettingsReadAllExisting {
            get {
                return ((bool)(this["PnlNLogDirectorySettingsReadAllExisting"]));
            }
            set {
                this["PnlNLogDirectorySettingsReadAllExisting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogWindowDrawGrid {
            get {
                return ((bool)(this["LogWindowDrawGrid"]));
            }
            set {
                this["LogWindowDrawGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FrmMainCheckForUpdateOnStartup {
            get {
                return ((bool)(this["FrmMainCheckForUpdateOnStartup"]));
            }
            set {
                this["FrmMainCheckForUpdateOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingsUpgradeRequired {
            get {
                return ((bool)(this["SettingsUpgradeRequired"]));
            }
            set {
                this["SettingsUpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DockLayoutWinDebugReceiver {
            get {
                return ((string)(this["DockLayoutWinDebugReceiver"]));
            }
            set {
                this["DockLayoutWinDebugReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,1,1,1,1,1")]
        public string ColumnVisibleLog4NetDirReceiver {
            get {
                return ((string)(this["ColumnVisibleLog4NetDirReceiver"]));
            }
            set {
                this["ColumnVisibleLog4NetDirReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100,100,100,100,100,1024")]
        public string ColumnWidthLog4NetDirReceiver {
            get {
                return ((string)(this["ColumnWidthLog4NetDirReceiver"]));
            }
            set {
                this["ColumnWidthLog4NetDirReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,1,1,1,1,1")]
        public string ColumnVisibleLog4NetUdpReceiver {
            get {
                return ((string)(this["ColumnVisibleLog4NetUdpReceiver"]));
            }
            set {
                this["ColumnVisibleLog4NetUdpReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,1,1,1,1,1")]
        public string ColumnVisibleLog4NetFileReceiver {
            get {
                return ((string)(this["ColumnVisibleLog4NetFileReceiver"]));
            }
            set {
                this["ColumnVisibleLog4NetFileReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100,100,100,100,100,1024")]
        public string ColumnWidthLog4NetUdpReceiver {
            get {
                return ((string)(this["ColumnWidthLog4NetUdpReceiver"]));
            }
            set {
                this["ColumnWidthLog4NetUdpReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100,100,100,100,100,1024")]
        public string ColumnWidthLog4NetFileReceiver {
            get {
                return ((string)(this["ColumnWidthLog4NetFileReceiver"]));
            }
            set {
                this["ColumnWidthLog4NetFileReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,1,1,1,1,1")]
        public string ColumnVisibleNLogDirReceiver {
            get {
                return ((string)(this["ColumnVisibleNLogDirReceiver"]));
            }
            set {
                this["ColumnVisibleNLogDirReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,1,1,1,1,1")]
        public string ColumnVisibleNLogFileReceiver {
            get {
                return ((string)(this["ColumnVisibleNLogFileReceiver"]));
            }
            set {
                this["ColumnVisibleNLogFileReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,1,1,1,1,1")]
        public string ColumnVisibleNLogTcpReceiver {
            get {
                return ((string)(this["ColumnVisibleNLogTcpReceiver"]));
            }
            set {
                this["ColumnVisibleNLogTcpReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,1,1,1,1,1")]
        public string ColumnVisibleNLogUdpReceiver {
            get {
                return ((string)(this["ColumnVisibleNLogUdpReceiver"]));
            }
            set {
                this["ColumnVisibleNLogUdpReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100,100,100,100,100,1024")]
        public string ColumnWidthNLogDirReceiver {
            get {
                return ((string)(this["ColumnWidthNLogDirReceiver"]));
            }
            set {
                this["ColumnWidthNLogDirReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100,100,100,100,100,1024")]
        public string ColumnWidthNLogFileReceiver {
            get {
                return ((string)(this["ColumnWidthNLogFileReceiver"]));
            }
            set {
                this["ColumnWidthNLogFileReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100,100,100,100,100,1024")]
        public string ColumnWidthNLogTcpReceiver {
            get {
                return ((string)(this["ColumnWidthNLogTcpReceiver"]));
            }
            set {
                this["ColumnWidthNLogTcpReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100,100,100,100,100,1024")]
        public string ColumnWidthNLogUdpReceiver {
            get {
                return ((string)(this["ColumnWidthNLogUdpReceiver"]));
            }
            set {
                this["ColumnWidthNLogUdpReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,1,1,1,1,1,1,1")]
        public string ColumnVisibleEventlogReceiver {
            get {
                return ((string)(this["ColumnVisibleEventlogReceiver"]));
            }
            set {
                this["ColumnVisibleEventlogReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100,100,100,100,100,100,100,1024")]
        public string ColumnWidthEventlogReceiver {
            get {
                return ((string)(this["ColumnWidthEventlogReceiver"]));
            }
            set {
                this["ColumnWidthEventlogReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,1,1,1,1,1,1")]
        public string ColumnVisibleSyslogFileReceiver {
            get {
                return ((string)(this["ColumnVisibleSyslogFileReceiver"]));
            }
            set {
                this["ColumnVisibleSyslogFileReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100,100,100,100,100,100,1024")]
        public string ColumnWidthSyslogFileReceiver {
            get {
                return ((string)(this["ColumnWidthSyslogFileReceiver"]));
            }
            set {
                this["ColumnWidthSyslogFileReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,1,1,1,1,1,1")]
        public string ColumnVisibleSyslogUdpReceiver {
            get {
                return ((string)(this["ColumnVisibleSyslogUdpReceiver"]));
            }
            set {
                this["ColumnVisibleSyslogUdpReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100,100,100,100,100,100,1024")]
        public string ColumnWidthSyslogUdpReceiver {
            get {
                return ((string)(this["ColumnWidthSyslogUdpReceiver"]));
            }
            set {
                this["ColumnWidthSyslogUdpReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,1,1,1,1")]
        public string ColumnVisibleWinDebugReceiver {
            get {
                return ((string)(this["ColumnVisibleWinDebugReceiver"]));
            }
            set {
                this["ColumnVisibleWinDebugReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100,100,100,100,1024")]
        public string ColumnWidthWinDebugReceiver {
            get {
                return ((string)(this["ColumnWidthWinDebugReceiver"]));
            }
            set {
                this["ColumnWidthWinDebugReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int WaitCursorTimeout {
            get {
                return ((int)(this["WaitCursorTimeout"]));
            }
            set {
                this["WaitCursorTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlCustomUdpSettingsInterface {
            get {
                return ((string)(this["PnlCustomUdpSettingsInterface"]));
            }
            set {
                this["PnlCustomUdpSettingsInterface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7071")]
        public int PnlCustomUdpSettingsPort {
            get {
                return ((int)(this["PnlCustomUdpSettingsPort"]));
            }
            set {
                this["PnlCustomUdpSettingsPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DockLayoutCustomUdpReceiver {
            get {
                return ((string)(this["DockLayoutCustomUdpReceiver"]));
            }
            set {
                this["DockLayoutCustomUdpReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlCustomUdpSettingsMulticastAddress {
            get {
                return ((string)(this["PnlCustomUdpSettingsMulticastAddress"]));
            }
            set {
                this["PnlCustomUdpSettingsMulticastAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PnlCustomUdpSettingsJoinMulticast {
            get {
                return ((bool)(this["PnlCustomUdpSettingsJoinMulticast"]));
            }
            set {
                this["PnlCustomUdpSettingsJoinMulticast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PnlLog4NetUdpSettingsJoinMulticast {
            get {
                return ((bool)(this["PnlLog4NetUdpSettingsJoinMulticast"]));
            }
            set {
                this["PnlLog4NetUdpSettingsJoinMulticast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlLog4NetUdpSettingsMulticastAddress {
            get {
                return ((string)(this["PnlLog4NetUdpSettingsMulticastAddress"]));
            }
            set {
                this["PnlLog4NetUdpSettingsMulticastAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PnlNLogUdpSettingsJoinMulticast {
            get {
                return ((bool)(this["PnlNLogUdpSettingsJoinMulticast"]));
            }
            set {
                this["PnlNLogUdpSettingsJoinMulticast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlNLogUdpSettingsMulticastAddress {
            get {
                return ((string)(this["PnlNLogUdpSettingsMulticastAddress"]));
            }
            set {
                this["PnlNLogUdpSettingsMulticastAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DockLayoutCustomDirReceiver {
            get {
                return ((string)(this["DockLayoutCustomDirReceiver"]));
            }
            set {
                this["DockLayoutCustomDirReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlCustomDirectorySettingsDirectory {
            get {
                return ((string)(this["PnlCustomDirectorySettingsDirectory"]));
            }
            set {
                this["PnlCustomDirectorySettingsDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlCustomDirectorySettingsPattern {
            get {
                return ((string)(this["PnlCustomDirectorySettingsPattern"]));
            }
            set {
                this["PnlCustomDirectorySettingsPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PnlCustomDirectorySettingsReadAllExisting {
            get {
                return ((bool)(this["PnlCustomDirectorySettingsReadAllExisting"]));
            }
            set {
                this["PnlCustomDirectorySettingsReadAllExisting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DockLayoutCustomTcpReceiver {
            get {
                return ((string)(this["DockLayoutCustomTcpReceiver"]));
            }
            set {
                this["DockLayoutCustomTcpReceiver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PnlCustomTcpSettingsInterface {
            get {
                return ((string)(this["PnlCustomTcpSettingsInterface"]));
            }
            set {
                this["PnlCustomTcpSettingsInterface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PnlCustomTcpSettingsPort {
            get {
                return ((int)(this["PnlCustomTcpSettingsPort"]));
            }
            set {
                this["PnlCustomTcpSettingsPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MMM d HH:mm:ss")]
        public string PnlSyslogFileSettingsTimestampFormat {
            get {
                return ((string)(this["PnlSyslogFileSettingsTimestampFormat"]));
            }
            set {
                this["PnlSyslogFileSettingsTimestampFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MMM d HH:mm:ss")]
        public string PnlSyslogUdpSettingsTimestampFormat {
            get {
                return ((string)(this["PnlSyslogUdpSettingsTimestampFormat"]));
            }
            set {
                this["PnlSyslogUdpSettingsTimestampFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visual Studio Light")]
        public string ApplicationTheme {
            get {
                return ((string)(this["ApplicationTheme"]));
            }
            set {
                this["ApplicationTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1252")]
        public int PnlSyslogFileSettingsEncoding {
            get {
                return ((int)(this["PnlSyslogFileSettingsEncoding"]));
            }
            set {
                this["PnlSyslogFileSettingsEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1252")]
        public int PnlSyslogUdpSettingsEncoding {
            get {
                return ((int)(this["PnlSyslogUdpSettingsEncoding"]));
            }
            set {
                this["PnlSyslogUdpSettingsEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1252")]
        public int PnlNLogUdpSettingsEncoding {
            get {
                return ((int)(this["PnlNLogUdpSettingsEncoding"]));
            }
            set {
                this["PnlNLogUdpSettingsEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1252")]
        public int PnlNLogTcpSettingsEncoding {
            get {
                return ((int)(this["PnlNLogTcpSettingsEncoding"]));
            }
            set {
                this["PnlNLogTcpSettingsEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1252")]
        public int PnlNLogFileSettingsEncoding {
            get {
                return ((int)(this["PnlNLogFileSettingsEncoding"]));
            }
            set {
                this["PnlNLogFileSettingsEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1252")]
        public int PnlNLogDirectorySettingsEncoding {
            get {
                return ((int)(this["PnlNLogDirectorySettingsEncoding"]));
            }
            set {
                this["PnlNLogDirectorySettingsEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1252")]
        public int PnlLog4NetFileSettingsEncoding {
            get {
                return ((int)(this["PnlLog4NetFileSettingsEncoding"]));
            }
            set {
                this["PnlLog4NetFileSettingsEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1252")]
        public int PnlLog4NetDirectorySettingsEncoding {
            get {
                return ((int)(this["PnlLog4NetDirectorySettingsEncoding"]));
            }
            set {
                this["PnlLog4NetDirectorySettingsEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1252")]
        public int PnlLog4NetUdpSettingsEncoding {
            get {
                return ((int)(this["PnlLog4NetUdpSettingsEncoding"]));
            }
            set {
                this["PnlLog4NetUdpSettingsEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1252")]
        public int PnlCustomFileSettingsEncoding {
            get {
                return ((int)(this["PnlCustomFileSettingsEncoding"]));
            }
            set {
                this["PnlCustomFileSettingsEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1252")]
        public int PnlCustomDirectorySettingsEncoding {
            get {
                return ((int)(this["PnlCustomDirectorySettingsEncoding"]));
            }
            set {
                this["PnlCustomDirectorySettingsEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1252")]
        public int PnlCustomUdpSettingsEncoding {
            get {
                return ((int)(this["PnlCustomUdpSettingsEncoding"]));
            }
            set {
                this["PnlCustomUdpSettingsEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1252")]
        public int PnlCustomTcpSettingsEncoding {
            get {
                return ((int)(this["PnlCustomTcpSettingsEncoding"]));
            }
            set {
                this["PnlCustomTcpSettingsEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TimeShiftValue {
            get {
                return ((double)(this["TimeShiftValue"]));
            }
            set {
                this["TimeShiftValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TimeShiftUnitIndex {
            get {
                return ((int)(this["TimeShiftUnitIndex"]));
            }
            set {
                this["TimeShiftUnitIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1252")]
        public string PnlNLogDirSettingsEncoding {
            get {
                return ((string)(this["PnlNLogDirSettingsEncoding"]));
            }
            set {
                this["PnlNLogDirSettingsEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1252")]
        public string PnlCustomDirSettingsEncoding {
            get {
                return ((string)(this["PnlCustomDirSettingsEncoding"]));
            }
            set {
                this["PnlCustomDirSettingsEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseInvertedColorForSelection {
            get {
                return ((bool)(this["UseInvertedColorForSelection"]));
            }
            set {
                this["UseInvertedColorForSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color CodeElement_Identifier_ForegroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeElement_Identifier_ForegroundColor"]));
            }
            set {
                this["CodeElement_Identifier_ForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color CodeElement_Identifier_BackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeElement_Identifier_BackgroundColor"]));
            }
            set {
                this["CodeElement_Identifier_BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle CodeElement_Identifier_FontStyle {
            get {
                return ((global::System.Drawing.FontStyle)(this["CodeElement_Identifier_FontStyle"]));
            }
            set {
                this["CodeElement_Identifier_FontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FrmMainShowWelcomePage {
            get {
                return ((bool)(this["FrmMainShowWelcomePage"]));
            }
            set {
                this["FrmMainShowWelcomePage"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TRACE")]
        public string Log4NetLevelTrace {
            get {
                return ((string)(this["Log4NetLevelTrace"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEBUG")]
        public string Log4NetLevelDebug {
            get {
                return ((string)(this["Log4NetLevelDebug"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INFO")]
        public string Log4NetLevelInfo {
            get {
                return ((string)(this["Log4NetLevelInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WARN")]
        public string Log4NetLeveLWarning {
            get {
                return ((string)(this["Log4NetLeveLWarning"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ERROR")]
        public string Log4NetLevelError {
            get {
                return ((string)(this["Log4NetLevelError"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FATAL")]
        public string Log4NetLevelFatal {
            get {
                return ((string)(this["Log4NetLevelFatal"]));
            }
        }
    }
}
